### ISSUE TITLE
CI deployment of the website is incomplete

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lf-lang.github.io#125]
After merging https://github.com/lf-lang/lf-lang.github.io/pull/124, the newly added entry "Generic Reactors" under "Writing Reactos" in the handbook sidebar did not appear, although the page is there (https://www.lf-lang.org/docs/handbook/generics?target=cpp). A similar issue occurred in (https://github.com/lf-lang/lf-lang.github.io/pull/121), where renaming an entry let to CI errors. In both cases, the website compiled and run fine locally, but not in CI... This indicates that there must be some issue with our deployment process.

**Comment by lhstrh** [comment]
When built locally, the page also does not show up in the menu on my end. Could there be some uncommitted state that you have but we don't?

**Comment by cmnrd** [comment]
I tried again with the current main branch, and it works fine on my end. I simply run `yarn start` and got this:
![Screenshot_20230228_100110](https://user-images.githubusercontent.com/6460123/221804532-53ab635f-3e0e-4e58-bd88-e3e6103be9b3.png)
My git status is empty. I am also certain that I committed all the changes that I made by hand. If there are any other changes missing, they are both auto-generated and ignored by git.

**Comment by lhstrh** [comment]
Strange. The menu entry does not show up for me...

**Comment by cmnrd** [comment]
Is there any guideline on how new pages are supposed to be added? Maybe I missed something, but it looks to me like all the information should be available to the tools.

**Comment by lhstrh** [comment]
Did you consult the [README.md](https://github.com/lf-lang/lf-lang.github.io/blob/main/packages/documentation/README.md)?

**Comment by cmnrd** [comment]
I was not aware of this document. I now noticed that it is linked from the main README, but it is not too obvious.

Apparently, the file I edited manually in #124 gets automatically generated when running `yarn bootstrap`. It is strange to me that a file located in `scr/lib` gets generated, but Ok. I now edited the correct file and pushed a fix to main.

**Comment by lhstrh** [comment]
We inherited a lot of useful things but also quite a few strange ones, I agree...
