### ISSUE TITLE
Docs: trim trailing newlines from code samples

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lf-lang.github.io#153]
Properly formatted code ends with a newline, but in the code samples on the website this is undesirable. We should trim the extra newline is there is one.

**Comment by edwardalee** [comment]
I suggest removing all whitespace-only lines.  The code samples are meant to be very small. They don't really need extra space.

**Comment by edwardalee** [comment]
This is fixed in [release-5 4f8c49c84].

**Comment by lhstrh** [comment]
The link doesn't work?
