### ISSUE TITLE
Docs: Update Epoch installation instructions

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lf-lang.github.io#158]
**Page URL:** [Epoch IDE](https://www.lf-lang.org/docs/handbook/epoch-ide)

**Issue:** This refers to version 0.3 as the latest stable version and doesn't have info about the new `curl`-based installation mechanism.

**Recommended Fix:** This needs to be updated.

**Also:** The Epoch splash page still says its version is 0.4.1 Snapshot

**Comment by lhstrh** [comment]
Note: problems with the publication of nightly (evidenced by out-dated splash screen) are resolved in https://github.com/lf-lang/epoch/pull/46.
