### ISSUE TITLE
Avoid broken links

### ISSUE THREAD

**Issue by housengw** [lf-lang/lf-lang.github.io#160]
To guard against broken links on our website, there is tooling available. Should we add stale link checking as part of the CI? Looks like there are some tools that could help:
1. [markdown-link-check](https://github.com/tcort/markdown-link-check)
2. [brok](https://github.com/smallhadroncollider/brok)
3. [My Broken Link Checker (Github Action)](https://github.com/marketplace/actions/my-broken-link-checker)

**Comment by lhstrh** [comment]
Let's also revisit this one, @axmmisaka.

**Comment by axmmisaka** [comment]
Docusaurus will emit warning if the link is broken. We can make it more radical by making it not build if there's broken link.
