### ISSUE TITLE
Migrate to Docusaurus

### ISSUE THREAD

**Issue by axmmisaka** [lf-lang/lf-lang.github.io#184]
1. Archive the legacy website into `old` branch
2. Delete stale branches associated with legacy branch, and rebase current PRs into docusaurus
3. Make docusaurus the new "main"

https://github.com/axmmisaka/lf-docs-docusaurus

While it is not quite complete from a aesthetics perspective, I say it is more than ready and is as good as the current website......

**Comment by lhstrh** [comment]
:rocket: :rocket: :rocket:
