### ISSUE TITLE
Discuss if we need previews for PRs and if so where

### ISSUE THREAD

**Issue by axmmisaka** [lf-lang/lf-lang.github.io#195]
As this could be done easily with GH codespaces and potentially some screenshots

If we want them, we need to find a place to host a "francabot" account, for free potentially. I know:
1. Netlify
2. Vercel

**Comment by lhstrh** [comment]
It seems like having something like this might be overkill, especially given how easy it is to run the site locally or on a GitPod/Code space. Let's not invest time in setting this up for now.
