### ISSUE TITLE
README file is a bit thin

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lf-lang.github.io#215]
The README file does not really have enough information.  What is the difference between "Local Development" (`yarn start`) and "Build" (`yarn build`)? When should I do the latter?  What is "Deployment" and when should I do that?

**Comment by lhstrh** [comment]
I'd say it's too thick, actually, because the parts you have questions about are not relevant to us (we use a GitHub Action to deploy the website). I'll reorganize it.
