### ISSUE TITLE
The EPUB is difficult to maintain

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lf-lang.github.io#64]
In Node 17, the EPUB files produced by [`streampub`](https://github.com/iarna/streampub) are invalid because one of its dependencies is not up to date. An attempt to unzip one of them results in a message such as `bad CRC 2cab616f  (should be 00000000)`.

[This issue](https://github.com/nodejs/node/issues/37027) explains where (I think) the issue comes from.

To my knowledge, we have two options:
1. Do not produce the EPUB. This file format might not be popular enough to justify maintaining the EPUB.
1. Maintain our own fork of `streampub` that repairs the problem, and include it here as a submodule. The change required to fix the EPUBs is actually trivial: Just bump the version number of a single dependency. However, if we run into further problems of this sort, then we will probably be on our own to fix them since `streampub` does not appear to be actively maintained.

Does anyone have an opinion on how to proceed?

**Comment by lhstrh** [comment]
What about a third option: submit a PR to the upstream repo?

**Comment by edwardalee** [comment]
I would be fine with not producing an EPUB version.

**Comment by lhstrh** [comment]
@petervdonovan: did you end up submitting a PR with streampub? If not, I'd also be fine with letting go of the epub...

**Comment by petervdonovan** [comment]
> did you end up submitting a PR with streampub?

Oh, I did submit a PR with them, but it did not go anywhere. I should let go of it and proceed with the PDF generation; that effort just fell by the wayside for a while.

**Comment by lhstrh** [comment]
We ditched the epub when migrating to docusaurus.
