### ISSUE TITLE
Docs: LF diagrams not rendered in PDF.

### ISSUE THREAD

**Issue by lsk567** [lf-lang/lf-lang.github.io#79]
**Page URL:**  https://www.lf-lang.org/assets/lingua-franca-handbook_lf-c.pdf

**Issue:**  LF diagrams not rendered in PDF. See below.
<img width="811" alt="Screen Shot 2022-06-20 at 9 11 12 AM" src="https://user-images.githubusercontent.com/7968955/174643099-11f4fc3c-3e1c-40fa-9c83-dc25cacbed00.png">

**Comment by lhstrh** [comment]
Not pertinent to this issue, but I think the file name should be something like `lingua-franca-handbook-c.pdf` (not and not feature `lf-c`, which is redundant).
