### ISSUE TITLE
Docs: Unfortunate end-of-file line endings

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lf-lang.github.io#99]
Unfortunately, our practice of adding line endings at the end of files has an unfortunate side effect in the website. It makes every code listing one line longer with a blank line at the end.  I had been deliberately avoiding adding line endings on the last line of all the `.lf` files in the website.  See image below:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/8513334/180645087-48220ac3-8b81-4563-9826-4229bfda9461.png">
Notice that the first code snippet has a blank line at the end. This is because that snippet is imported from a `.lf` file, and someone added line endings to all those files.  The second code snippet does not have a blank line because it is not imported from a `.lf` file.

**Comment by lhstrh** [comment]
Seems like something that could be easily fixed by processing the string. That will be more robust than relying on a convention.

**Comment by axmmisaka** [comment]
I think our new website do not suffer from this issue, so closing this.
